### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by Accefy** [Permify/permify-go#1]
<img width="1119" alt="error_permify_go_get" src="https://user-images.githubusercontent.com/63685585/219474080-6ef275e6-0592-49a7-a476-6730342b870a.png">
following the instructions to add the package to the project found this issue.
Cleaned the mod cache, but the same result.

**Comment by tolgaOzen** [comment]
Hi [@Accefy ](https://github.com/accefy) we solved the issue! Could you install the latest version of permify-go (0.3.1) and test it. You can try with this command:

`go get github.com/Permify/permify-go@v0.3.1`

We can close this issue afterwards.

**Comment by Accefy** [comment]
extra quick! thank you.

**Comment by Accefy** [comment]
sorry, I close it prematurely:
![error_permify](https://user-images.githubusercontent.com/63685585/219494367-43dcc835-b50d-4d8d-840d-45eebd41b67f.png)

**Comment by tolgaOzen** [comment]
Hi, [@Accefy ](https://github.com/accefy) can you try with this command `go get github.com/Permify/permify-go@latest ` after that if it doesn't work can you share the screen shot of the server.go file with us?

**Comment by Accefy** [comment]
I saw that there is a new version (0.3.2) but the issue still remains. 
Here is the full code:
<img width="659" alt="Screenshot at Feb 16 22-33-37" src="https://user-images.githubusercontent.com/63685585/219526956-31c151a1-e3c4-45ee-99ba-e92e6f67c628.png">

**Comment by tolgaOzen** [comment]
After running go mod tidy command, does your go.mod file look like this?

<img width="907" alt="Screenshot 2023-02-16 at 6 28 38 PM" src="https://user-images.githubusercontent.com/39353278/219534264-3828d04d-33fb-4759-80cf-9c145258a2e8.png">

**Comment by Accefy** [comment]
This is the result:
![Screenshot at Feb 17 09-21-21](https://user-images.githubusercontent.com/63685585/219652401-2789af03-2aba-448b-814b-efcae5e1b2b3.png)

**Comment by tolgaOzen** [comment]
Does it give the same error as before or has it changed?

**Comment by Accefy** [comment]
Hello, I apologize for the late response, but I was trying to testing out correctly. The issue is solved, but I had to change the import path from: 
`github.com/Permify/permify-go`
to:
`github.com/Permify/permify-go/v1`
I recommend to change this line in the readme.

**Comment by tolgaOzen** [comment]
Hi @Accefy, we'll update the read.me file accordingly.

**Comment by lekhanhtoan37** [comment]
Update readme please, still

```go
import permify "github.com/Permify/permify-go"
```
